In [1]:
import tensorflow as tf

#벡터 정의
vec = tf.constant([10, 20, 30, 40, 50])
print(vec)

tf.Tensor([10 20 30 40 50], shape=(5,), dtype=int32)


In [2]:
print(vec[0])
print(vec[-1])

tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(50, shape=(), dtype=int32)


In [3]:
print(vec[:3])

tf.Tensor([10 20 30], shape=(3,), dtype=int32)


In [4]:
#행렬 정의
mat = tf.constant([[10, 20, 30],
                   [40, 50, 60]])

print(mat[0, 2])

tf.Tensor(30, shape=(), dtype=int32)


In [8]:
print(mat[0,:])

print(mat[:, 1])

print(mat[:,:])

tf.Tensor([10 20 30], shape=(3,), dtype=int32)
tf.Tensor([20 50], shape=(2,), dtype=int32)
tf.Tensor(
[[10 20 30]
 [40 50 60]], shape=(2, 3), dtype=int32)


In [11]:
#3차원 텐서 정의
tensor = tf.constant([[[10, 20, 30],
                      [40, 50, 60]],
                      [[-10, -20, -30],
                      [-40, -50, -60]]])

print(tensor)

tf.Tensor(
[[[ 10  20  30]
  [ 40  50  60]]

 [[-10 -20 -30]
  [-40 -50 -60]]], shape=(2, 2, 3), dtype=int32)


In [12]:
print(tensor[0,:,:])

print(tensor[:, :2, :2])

tf.Tensor(
[[10 20 30]
 [40 50 60]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[[ 10  20]
  [ 40  50]]

 [[-10 -20]
  [-40 -50]]], shape=(2, 2, 2), dtype=int32)
