In [1]:
import tensorflow as tf

tensor1 = tf.constant([[0, 1, 2],
                       [3, 4, 5]])

print(tensor1)

tf.Tensor(
[[0 1 2]
 [3 4 5]], shape=(2, 3), dtype=int32)


In [3]:
tensor_var1 = tf.Variable(tensor1)

print(tensor_var1)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5]], dtype=int32)>


In [4]:
print("이름 : ", tensor_var1.name)
print("크기 : ", tensor_var1.shape)
print("자료형 : ", tensor_var1.dtype)
print("배열 : ", tensor_var1.numpy())

이름 :  Variable:0
크기 :  (2, 3)
자료형 :  <dtype: 'int32'>
배열 :  [[0 1 2]
 [3 4 5]]


In [6]:
#assign 메서드 => 변수에 새로운 데이터를 할당한다. (원래 변수의 크기와 자료형이 동일해야한다.)
tensor_var1.assign([[1, 1, 1],
                    [2, 2, 2]])

print(tensor_var1)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 1, 1],
       [2, 2, 2]], dtype=int32)>


In [7]:
#convert_to_tensor 메서드 => 텐서플로 변수를 텐서로 변환한다.
tensor2 = tf.convert_to_tensor(tensor_var1)
print(tensor2)

tf.Tensor(
[[1 1 1]
 [2 2 2]], shape=(2, 3), dtype=int32)


In [9]:
#텐서플로 변수는 name 속성을 따로 가진다.
tensor_var2 = tf.Variable(tensor2, name = 'New Name')
print(tensor_var2.name)

New Name:0


In [10]:
tensor_var1 + tensor_var2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 2, 2],
       [4, 4, 4]], dtype=int32)>