In [2]:
import tensorflow as tf
import numpy as np

#1차원 배열 정리
py_list = [10., 20., 30.]
num_arr = np.array([10.,10., 10.])

vec1 = tf.constant(py_list, dtype=tf.float32)
vec2 = tf.constant(num_arr, dtype=tf.float32)

print("vec1 : ", vec1)
print("vec2 : ", vec2)

vec1 :  tf.Tensor([10. 20. 30.], shape=(3,), dtype=float32)
vec2 :  tf.Tensor([10. 10. 10.], shape=(3,), dtype=float32)


In [3]:
print(tf.rank(vec1))
print(tf.rank(vec2))

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)


In [4]:
add1 = tf.math.add(vec1, vec2)
print("result : ", add1)
print("rank : ", tf.rank(add1)) #element by element adding

result :  tf.Tensor([20. 30. 40.], shape=(3,), dtype=float32)
rank :  tf.Tensor(1, shape=(), dtype=int32)


In [6]:
#same with upper
add2 = vec1 + vec2
print("result : ", add2)
print("rank : ", tf.rank(add2))

result :  tf.Tensor([20. 30. 40.], shape=(3,), dtype=float32)
rank :  tf.Tensor(1, shape=(), dtype=int32)


In [8]:
#reduce_sum => 벡터 구성 원소 전체 합.
print(tf.reduce_sum(vec1))
print(tf.rank(tf.reduce_sum(vec1)))

tf.Tensor(60.0, shape=(), dtype=float32)
tf.Tensor(0, shape=(), dtype=int32)


In [9]:
#square => 벡터 구성 원소 각각 제곱
print(tf.math.square(vec1))
print(tf.rank(tf.math.square(vec1)))

tf.Tensor([100. 400. 900.], shape=(3,), dtype=float32)
tf.Tensor(1, shape=(), dtype=int32)


In [10]:
#파이썬 연산도 사용 가능
print(vec1 + 1)
print(vec1 ** 2)
print(vec1 ** 0.5)

tf.Tensor([11. 21. 31.], shape=(3,), dtype=float32)
tf.Tensor([100. 400. 900.], shape=(3,), dtype=float32)
tf.Tensor([3.1622777 4.472136  5.477226 ], shape=(3,), dtype=float32)
